apiVersion: apps/v1
kind: Deployment
metadata:
  name: okiugyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okiugyu
  template:
    metadata:
      labels:
        app: okiugyu
    spec:
      containers:
      - image: okteto.dev/okiugyu:latest
        name: okiugyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "83ac0ea6-06cf-45e1-bcbb-a1669b12e154"
        - name: Vless_Path
          value: "/vldawqhegsghj"
        - name: Vmess_UUID
          value: "83ac0ea6-06cf-45e1-bcbb-a1669b12e154"
        - name: Vmess_Path
          value: "/vmlkjhesghhuyt"
        - name: Share_Path
          value: "/v2link"
