apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnhpiusdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnhpiusdf
  template:
    metadata:
      labels:
        app: mnhpiusdf
    spec:
      containers:
      - image: okteto.dev/mnhpiusdf:latest
        name: mnhpiusdf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d2a15f5c-87b7-4ec6-afc4-ad69404c1f2e"
        - name: Vless_Path
          value: "/vldawqhegsghj"
        - name: Vmess_UUID
          value: "d2a15f5c-87b7-4ec6-afc4-ad69404c1f2e"
        - name: Vmess_Path
          value: "/vmlkjhesghhuyt"
        - name: Share_Path
          value: "/v2link"
